language: php

sudo: false

env:
  global:
    - INFECTION_FLAGS='--threads=4 --min-msi=62 --min-covered-msi=72 --coverage=coverage --log-verbosity=none'
    - PHPUNIT_BIN='vendor/bin/phpunit --coverage-clover=clover.xml --coverage-xml=coverage/coverage-xml --log-junit=coverage/phpunit.junit.xml'
    - secure: FN+jF2w1O7bUWiDsLIvIfx2+vW6IsA2XfLc8l7CtPCIAvEnwYEs3ma7PuQsniFe1p2EPqsHz1oKCnctMCcPuzTi+r131nmfF3erzLy5LLnQzmEmCgbxTOLyMFEayfFSpzyZ7LJ+fFIVRJ5XyaDKv3PHYttioqO+M3WU7M8641zjnGy9nsZdRbuf4tRIQN1cW024zWmN2XO35F+j1bnyaxKHmXHNIW0fuMF/QtPaOM1ZeK0R/dSVY0x0hfe7/gfpnseG9Ssdks3Y7cn67Q5Rzdtxw7DkF6IbFdzArQf/SeGwgfNtPFo7kroHR9WfSE90CH7rdPSvXRZ4krFPx08JyuuiLp62xDf3m8Gr9fUWseZTgP1dT/pKyFEjTQqvIwszWSo8Lm/nHcSCT5SVGx5bEbGbXY/x3OjOWA4f5O5gYS8y+P9+DabrtpEFxU+eBY7l24Ida0n06eiuy6MrE5IJcQ5HcyyyVdVfJl9HRJDFRX97YT1SM/AQZYq7dCatK9IL0CAycPUifI7LpZ5XxXmWld+iWEevd7Hkb+/07FvVyh5GiM+jaokcoSgawwbNqRnGv2Pt07SXYNYY0AhiYZVsByG1pnwdvGVioB86NGo7GKq2dZqeqD0WsP+nU5Js0Wt/VaUuv2NG3LG90twqjBkB0RtM4dkaV6Oul6OGMVsv7Y1w=
    - secure: HBrSoww/XXS8mY/COGczd9fsmI72irr5i5u4sNqhCtoj4htVv8hkNQkTF1H6+6jby/blEkMzeuSfwf3EXDDSw+tH4VdWjI+/BZaydy9Nbaac+Gca7h35g0atAxyJg/o/ewSFystlz6fZJwLTatAbRMsDOM2yXfE0mjv97J0sL2zmjzEfjVgqk4feXlmViUlvNv6xSoZXcjoO19AO+V/dCKk2kfsNzmyizATUWeb1BOy6sY22qVukqFjvYxw/PXvpf1b0D9+YrXYfAP4087H0EcvrAg5124vdPp1LZl0FIS/+hieZo8BC5r6MugklQOetUFxRAOuofjCnroIZshvTuLrvF54S3nvSqjzx+H+J6bc8d87DIM5ibzkS3OLWdJ/NvQmBz+/usMFRxS4+4vUFmYghz5MP1/SieSkKXmdbOjbypk96arKKBtAhp7fwMIyACkuId32bMn4617ScRh1BOIsOabi8QbKqPLSuj5lk0yru6lorMwp64QDp6NR5EdUv07dHu8PCIlCOnOsJzTpo05C8LWgbT8TmMzEmRv1Itw+M3O/XIdN9GudCODS7yO6ukEBMEhU1mNgWjdeMUNZd8WlP8M3PvfNSNbIwDQAE45r4YC8vS7R3Fcwt94J9uAdoS9DrO0XeDTOam6iPBXLFjXacrK7M6JS0ERpEziPo5DY=
cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

addons:
  apt:
    packages:
    - expect

before_install:
  - source .ci/xdebug.sh
  - xdebug-disable

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      install:
        - composer install
      script:
        - make analyze --keep-going

    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.1
      install:
        - composer install
        - |
          if [ "${SYMFONY_VERSION}" != "" ]; then
            composer config --unset platform
            composer require \
            symfony/console:${SYMFONY_VERSION} \
            symfony/filesystem:${SYMFONY_VERSION} \
            symfony/process:${SYMFONY_VERSION} \
            symfony/finder:${SYMFONY_VERSION} \
            symfony/yaml:${SYMFONY_VERSION}
          fi
      script:
        - if [[ $PHPDBG != 1 ]]; then xdebug-enable; fi
        - if [[ $PHPDBG != 1 ]]; then $PHPUNIT_BIN; else phpdbg -qrr $PHPUNIT_BIN; fi
        - |
          if [[ "${SYMFONY_VERSION}" != "" ]]; then
            ./tests/e2e_tests bin/infection;
          else
            make build/bin/infection.phar;
            ./tests/e2e_tests build/bin/infection.phar;
          fi
        - if [[ $NO_DEBUGGER == 1 ]]; then xdebug-disable; fi
        - |
          if [[ $PHPDBG != 1 ]]; then
            bin/infection $INFECTION_FLAGS;
          else
            phpdbg -qrr bin/infection $INFECTION_FLAGS;
          fi

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    -
      <<: *STANDARD_TEST_JOB
      php: 7.1
      env: NO_DEBUGGER=1

    -
      <<: *STANDARD_TEST_JOB
      php: 7.1
      env: PHPDBG=1

    -
      <<: *STANDARD_TEST_JOB
      php: 7.1
      env: SYMFONY_VERSION="^4.0"

    -
      <<: *STANDARD_TEST_JOB
      php: 7.1
      env: SYMFONY_VERSION="^4.0" PHPDBG=1

    -
      <<: *STANDARD_TEST_JOB
      php: 7.2

    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: NO_DEBUGGER=1

    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: PHPDBG=1

    -
      <<: *STANDARD_TEST_JOB
      php: 7.1
      env: SYMFONY_VERSION="^4.0"

    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: SYMFONY_VERSION="^4.0" PHPDBG=1

    -
      <<: *STANDARD_TEST_JOB
      php: nightly
      env: PHPDBG=1

      script:
        # We don't have xdebug on the nightly build, so we always run with phpdbg.
        - make build/bin/infection.phar;
        - ./tests/e2e_tests build/bin/infection.phar;
        - phpdbg -qrr $PHPUNIT_BIN
        - phpdbg -qrr bin/infection $INFECTION_FLAGS

    - stage: Deploy
      php: 7.2
      install:
        - composer install
      script:
        make build/bin/infection.phar;
      before_deploy:
        - echo $DECRYPT_KEY | gpg --passphrase-fd 0 .ci/keys.asc.gpg
        - gpg --batch --yes --import .ci/keys.asc
        - echo $SIGN_KEY | gpg --passphrase-fd 0 -u C5095986493B4AA0 --armor --detach-sig build/bin/infection.phar

      deploy:
        provider: releases
        api_key:
          secure: JtdvJBE2ARf6VWN5KlXAburz3FZMriiXBHEdeIocHePBAzgYW7tVMksJR5N3azrE3KjhftMEukXtA1k5VfAGdLCSm6nKGsZwolkd24ryG7PYNuAdFWfbau8QQXn6aLFesF2lkTq89+PqxAdVjwXNgFA7ble3vL66Ogabff6gov6QwT9vDrTqwLmWNGwbt9QB32IE9yVPjW/3lk4MAkMHtKDr2DElyeT2CRRuPuUCA+zNwoGG95wqLAD/RwjsqR3GjotzDKrldqog9jU2OQptUc3BgdKlYR1AzdknxJYnT7a5CRVdmSOEfD9IrDqlYEzn9pHav+Sk4KD2KNKsALQGk/w16BqncN2uyOexUTzXvnDd27G4ZYy+1OsXMdYMhF5ffwj7EqNLm8XfLPtHHV0/FUJY9kkrbf9+wQVjDQmMJLLIiBSt3vuY0ya5SVW8thtjlF2j67smamNe4hDhditBipto+9Y5vI4AYhcm4CQlqP8BVbw3/LgGAl/dJR5ohM7PFZH3EUE1AojBaEXfUymlICdFVZFJbB0D/AM8jSqNmWBQu9QX3MURhT5xLSwc+kir2izQaEo/GQz79AifqkUJgSCzpRUJntCN8A7yk1uxDZDONbINF3ReuF+nqu7GMksgKZLCGbOIaBl9of24K5BeTqxgcEykiHFFY7X9QdI3Dyo=
        file:
          - build/bin/infection.phar
          - build/bin/infection.phar.asc
        skip_cleanup: true
        on:
          tags: true
          repo: infection/infection

  allow_failures:
    - php: nightly
      env: PHPDBG=1
